onerror {resume}
add list -width 13 /cputop/clk
add list /cputop/reset
add list /cputop/pcenable
add list /cputop/ifrenable
add list /cputop/test
add list /cputop/t_cpu/m_pc/clk
add list /cputop/t_cpu/m_pc/reset
add list /cputop/t_cpu/m_pc/pcenable
add list /cputop/t_cpu/m_pc/pcin
add list /cputop/t_cpu/m_pc/pcout
add list /cputop/clk
add list /cputop/reset
add list /cputop/pcenable
add list /cputop/ifrenable
add list /cputop/test
add list /cputop/t_cpu/clk
add list /cputop/t_cpu/reset
add list /cputop/t_cpu/pcenable
add list /cputop/t_cpu/ifrenable
add list /cputop/t_cpu/pcin
add list /cputop/t_cpu/pcout
add list /cputop/t_cpu/pc_addout
add list /cputop/t_cpu/ifrout
add list /cputop/t_cpu/signout
add list /cputop/t_cpu/pc_naddout
add list /cputop/t_cpu/pc_mux1out
add list /cputop/t_cpu/jout
add list /cputop/t_cpu/regdstout
add list /cputop/t_cpu/rd1
add list /cputop/t_cpu/rd2
add list /cputop/t_cpu/alusrcout
add list /cputop/t_cpu/result
add list /cputop/t_cpu/rd
add list /cputop/t_cpu/memtoregout
add list /cputop/t_cpu/jump
add list /cputop/t_cpu/branch
add list /cputop/t_cpu/memtoreg
add list /cputop/t_cpu/memwrite
add list /cputop/t_cpu/memread
add list /cputop/t_cpu/alusrc
add list /cputop/t_cpu/regwrite
add list /cputop/t_cpu/regdst
add list /cputop/t_cpu/zero
add list /cputop/t_cpu/aluop
add list /cputop/t_cpu/aluopration
add list /cputop/t_cpu/redwrite
add list /cputop/t_cpu/m_pc/clk
add list /cputop/t_cpu/m_pc/reset
add list /cputop/t_cpu/m_pc/pcenable
add list /cputop/t_cpu/m_pc/pcin
add list /cputop/t_cpu/m_pc/pcout
add list /cputop/t_cpu/m_pc_add/pc_addin
add list /cputop/t_cpu/m_pc_add/pc_addout
add list /cputop/t_cpu/m_ifr/ifrin
add list /cputop/t_cpu/m_ifr/reset
add list /cputop/t_cpu/m_ifr/ifrenable
add list /cputop/t_cpu/m_ifr/ifrout
add list /cputop/t_cpu/m_ifr/data
add list /cputop/t_cpu/m_control_unit/jump
add list /cputop/t_cpu/m_control_unit/branch
add list /cputop/t_cpu/m_control_unit/memtoreg
add list /cputop/t_cpu/m_control_unit/memwrite
add list /cputop/t_cpu/m_control_unit/memread
add list /cputop/t_cpu/m_control_unit/alusrc
add list /cputop/t_cpu/m_control_unit/regwrite
add list /cputop/t_cpu/m_control_unit/regdst
add list /cputop/t_cpu/m_control_unit/aluop
add list /cputop/t_cpu/m_control_unit/op
add list /cputop/t_cpu/m_sign_extend/signin
add list /cputop/t_cpu/m_sign_extend/signout
add list /cputop/t_cpu/m_pc_nadd/pc_naddin1
add list /cputop/t_cpu/m_pc_nadd/pc_naddin2
add list /cputop/t_cpu/m_pc_nadd/pc_naddout
add list /cputop/t_cpu/m_pc_mux1/in0
add list /cputop/t_cpu/m_pc_mux1/in1
add list /cputop/t_cpu/m_pc_mux1/zero
add list /cputop/t_cpu/m_pc_mux1/branch
add list /cputop/t_cpu/m_pc_mux1/pc_mux1out
add list /cputop/t_cpu/m_pc_shift/jin
add list /cputop/t_cpu/m_pc_shift/pc_addout
add list /cputop/t_cpu/m_pc_shift/jout
add list /cputop/t_cpu/m_pc_mux2/in0
add list /cputop/t_cpu/m_pc_mux2/in1
add list /cputop/t_cpu/m_pc_mux2/jump
add list /cputop/t_cpu/m_pc_mux2/pc_mux2out
add list /cputop/t_cpu/m_regdst/in0
add list /cputop/t_cpu/m_regdst/in1
add list /cputop/t_cpu/m_regdst/jump
add list /cputop/t_cpu/m_regdst/pc_mux2out
add list /cputop/t_cpu/m_id/rr1
add list /cputop/t_cpu/m_id/rr2
add list /cputop/t_cpu/m_id/wr
add list /cputop/t_cpu/m_id/wd
add list /cputop/t_cpu/m_id/rd1
add list /cputop/t_cpu/m_id/rd2
add list /cputop/t_cpu/m_id/reset
add list /cputop/t_cpu/m_id/regwrite
add list /cputop/t_cpu/m_alusrc/in0
add list /cputop/t_cpu/m_alusrc/in1
add list /cputop/t_cpu/m_alusrc/jump
add list /cputop/t_cpu/m_alusrc/pc_mux2out
add list /cputop/t_cpu/m_alucontrol/aluop
add list /cputop/t_cpu/m_alucontrol/func
add list /cputop/t_cpu/m_alucontrol/aluopration
add list /cputop/t_cpu/m_alu/ina
add list /cputop/t_cpu/m_alu/inb
add list /cputop/t_cpu/m_alu/result
add list /cputop/t_cpu/m_alu/zero
add list /cputop/t_cpu/m_alu/aluop
add list /cputop/t_cpu/m_alu/reset
add list /cputop/t_cpu/m_mem/memread
add list /cputop/t_cpu/m_mem/memwrite
add list /cputop/t_cpu/m_mem/reset
add list /cputop/t_cpu/m_mem/address
add list /cputop/t_cpu/m_mem/wd
add list /cputop/t_cpu/m_mem/rd
add list /cputop/t_cpu/m_memtoreg/in0
add list /cputop/t_cpu/m_memtoreg/in1
add list /cputop/t_cpu/m_memtoreg/jump
add list /cputop/t_cpu/m_memtoreg/pc_mux2out
add list /cputop/t_cpu/m_ifr/ifrin
add list /cputop/t_cpu/m_ifr/reset
add list /cputop/t_cpu/m_ifr/ifrenable
add list /cputop/t_cpu/m_ifr/ifrout
add list /cputop/t_cpu/m_ifr/data
configure list -usestrobe 0
configure list -strobestart {0 ns} -strobeperiod {0 ns}
configure list -usesignaltrigger 1
configure list -delta all
configure list -signalnamewidth 0
configure list -datasetprefix 0
configure list -namelimit 5
